# Schema for the configuration files of the nopremium module.
nopremium.settings:
  type: config_object
  label: 'Node option premium settings'
  mapping:
    default_message:
      type: string
      label: 'Premium message'
    view_mode:
      type: string
      label: 'Premium view mode'
    teaser_view_mode:
      type: string
      label: 'Teaser view mode'